### ISSUE TITLE
Error Compiling Yang2Swagger

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/l3nm#108]
The following Yang block generates error during the yang2swagger compilation:

``
case match-flow {
  //uses l3vpn-svc:flow-definition;
  choice l3 {
    container ipv4 {
      uses packet-fields:acl-ip-header-fields;
      uses packet-fields:acl-ipv4-header-fields;
      description
        "Rule set that matches IPv4 header.";
    }
    container ipv6 {
      uses packet-fields:acl-ip-header-fields;
      uses packet-fields:acl-ipv6-header-fields;
      description
        "Rule set that matches IPv6 header.";
    }
    description
      "Either IPv4 or IPv6.";
  }
  choice l4 {
    container tcp {
      uses packet-fields:acl-tcp-header-fields;
      uses ports;
      description
        "Rule set that matches TCP header.";
    }
    container udp {
      uses packet-fields:acl-udp-header-fields;
      uses ports;
      description
        "Rule set that matches UDP header.";
    }
    description
      "Can be TCP or UDP";
  }
}

**Comment by boucadair** [comment]
The module compiles well with pyang. 

What error are you getting?

**Comment by sbarguil** [comment]
Yes, pyang works fine.

However with the yang2swagger. It returns the following error:


```
java -jar /home/tid/.m2/repository/com/mrv/yangtools/swagger-generator-cli/1.1.14-SNAPSHOT/swagger-generator-cli-1.1.14-SNAPSHOT-executable.jar -yang-dir IETF-03/ -format json -content-type application/json -output /home/tid/yang/l3nm/IETF-03/l3nm.json ietf-l3vpn-ntw

2020-04-20 14:07:29,155 [main] WARN  c.m.y.c.i.OptimizingDataObjectBuilder - Multiple inheritance for (urn:ietf:params:xml:ns:yang:ietf-l3vpn-ntw?revision=2020-04-03)udp
2020-04-20 14:07:29,158 [main] ERROR com.mrv.yangtools.codegen.main.Main - Error while generating Swagger
java.lang.NullPointerException: null
	at com.mrv.yangtools.codegen.impl.AbstractDataObjectBuilder.assignCaseMetadata(AbstractDataObjectBuilder.java:289)
	at com.mrv.yangtools.codegen.impl.AbstractDataObjectBuilder.lambda$null$17(AbstractDataObjectBuilder.java:229)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.mrv.yangtools.codegen.impl.AbstractDataObjectBuilder.structure(AbstractDataObjectBuilder.java:233)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.structure(OptimizingDataObjectBuilder.java:630)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.simple(OptimizingDataObjectBuilder.java:623)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.fromContainer(OptimizingDataObjectBuilder.java:268)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.model(OptimizingDataObjectBuilder.java:319)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.build(OptimizingDataObjectBuilder.java:222)
	at com.mrv.yangtools.codegen.impl.AbstractDataObjectBuilder.addModel(AbstractDataObjectBuilder.java:302)
	at com.mrv.yangtools.codegen.impl.OptimizingDataObjectBuilder.addModel(OptimizingDataObjectBuilder.java:426)
	at com.mrv.yangtools.codegen.impl.AbstractDataObjectBuilder.addModel(AbstractDataObjectBuilder.java:316)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:418)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$2(SwaggerGenerator.java:417)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:417)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$2(SwaggerGenerator.java:417)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:417)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$2(SwaggerGenerator.java:417)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:417)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$1(SwaggerGenerator.java:402)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:402)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.lambda$generate$0(SwaggerGenerator.java:361)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator$ModuleGenerator.generate(SwaggerGenerator.java:361)
	at com.mrv.yangtools.codegen.SwaggerGenerator.lambda$generate$1(SwaggerGenerator.java:313)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mrv.yangtools.codegen.SwaggerGenerator.generate(SwaggerGenerator.java:313)
	at com.mrv.yangtools.codegen.SwaggerGenerator.generate(SwaggerGenerator.java:275)
	at com.mrv.yangtools.codegen.main.Main.generate(Main.java:148)
	at com.mrv.yangtools.codegen.main.Main.main(Main.java:90)
```

If I document the block of code. It Goes well.

**Comment by boucadair** [comment]
@sbarguil: Do we still have this "bug"?
